spring:
  application:
    name: LibraryCatalog

  datasource:
    url: jdbc:postgresql://localhost:5432/library_catalog
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "0000"

  web:
    cors:
      allowed-origins: "http://localhost:8080"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # və ya 'create' ya da 'validate' ehtiyacına uyğun
    show-sql: true

server:
  port: 8080
